### ISSUE TITLE
Powershell script doesn't update in a call correctly

### ISSUE THREAD

**Issue by PrayerfulDrop** [EBOOZ/TeamsStatus#26]
If the computer goes to sleep and then awakens the powershell script ceases to update HA.  Also, the powershell script should force the first update based on the last activity state if the service is restarted verses waiting for a change.

**Comment by EBOOZ** [comment]
Your computer going into sleep is a bit strange, since you are in a call ;)

I don't experience the issue that you mentioned with the latest version of the script, and the status is updated based on the results from the logfile when the service starts and the Teams client is running. Please provide more details about this issue, or provide a possible solution. Thanks!

**Comment by PrayerfulDrop** [comment]
Found the app logic error.  I have submitted a change accordingly.  A shame you don't help troubleshoot the issue but that is ok I found the problem.  When RTC Monitor becomes fleshed out I will ensure to switch to a supported code set ASAP.
