### ISSUE TITLE
Multi-User?

### ISSUE THREAD

**Issue by ChrisPiel70** [EBOOZ/TeamsStatus#3]
Hello,

thanks for the Script, it works great (and much smaller solution than "Presencelight"). 

Is it possible to expand the function to alllow mutliple Users (each with there own Sensors)?

Like:
sensor.teams_username_status
sensor.teams_username_activity

My wife and I are both in home office and the kids are both having home schooling (also there are 4 People using Teams).

Best regards

**Comment by EBOOZ** [comment]
That would be definitely possible! The easiest way is when everybody uses his or her own machine.

Otherwise you would need to create 4 different services on one PC that all will monitor a different Teams logfile. The location of the logfile is `C:\Users\$UserName\AppData\Roaming\Microsoft\Teams\logs.txt` where $UserName is the logged in user.

Since the script is running in the system context, it cannot automatically detect the logged in user at this moment.

**Comment by EBOOZ** [comment]
Closing this issue. Feel free to reopen if things don't work out.
