### ISSUE TITLE
Implement support for Microsoft Teams Live Events

### ISSUE THREAD

**Issue by EBOOZ** [EBOOZ/TeamsStatus#4]
Currently the status is not updated when joining a Live Event. I need to dig into the Teams logfile to see if there is an common identifier to determine if a Live Event is joined via the client on your machine.

**Comment by eavanvalkenburg** [comment]
I just had a look and it seems joining a live event has the same log:
```
Thu Jan 14 2021 17:06:18 GMT+0100 (Central European Standard Time) <17964> -- info -- StatusIndicatorStateService: Added OnThePhone (current state: Busy -> OnThePhone)| profileType: AAD
Thu Jan 14 2021 17:06:18 GMT+0100 (Central European Standard Time) <17964> -- info -- Setting the taskbar overlay icon - On the phone 
```
So I'm not sure if my connection between the service and HA isn't working, but I have seen it working at some point, I also might misunderstand the logic.

edit: so that works for the Status, but when I run the Activity query I get zero returns, so I guess that one isn't updated by the live event.

**Comment by EBOOZ** [comment]
Thanks for digging into it! I've experienced the same as you until now.

One thing that I've noticed is a line with something like "Using WebView blablabla" that could indicate a Live Event is started. I'll definitely will have a look at a later moment.

**Comment by EBOOZ** [comment]
This has been fixed in https://github.com/EBOOZ/TeamsStatus/commit/e168739cd28a640cd84a6e2069807773cd13a8da
